import mapper from './mapper'

const raw = [
  '1:Percussion|Tumba Thump',
  '2:Percussion|Tumba Open',
  '3:Percussion|Quinto Slap',
  '4:Percussion|Quinto Open Trio *',
  '5:Percussion|Cajon 10 Open',
  '6:Percussion|Cajon 10 Open-Slap *',
  '7:Percussion|Cajon 12 Open',
  '8:Percussion|Cajon 12 Open-Slap *',
  '9:Percussion|Clave',
  '10:Percussion|Djembe 1 Open',
  '11:Percussion|Djembe 2 Mute',
  '12:Percussion|Djembe Slap',
  '13:Percussion|Bongo High Open-Slap *',
  '14:Percussion|Bongo Low Open-Rim *',
  '15:Percussion|Darbuka Center',
  '16:Percussion|Darbuka Rim',
  '17:Percussion|DS Tambourine',
  '18:Percussion|Udu Strike',
  '19:Percussion|Udu Scoop',
  '20:Percussion|Doumbek Center',
  '21:Percussion|Doumbek Rim',
  '22:Kick|Bop Kick',
  '23:Kick|General Kick',
  '24:Kick|Sleishman 20',
  '25:Kick|Tonal 1',
  '26:Kick|Ti BD 26 (Amped)',
  '27:Kick|Remo 18 Djembe (Beater)',
  '28:Snare|Sleishman Maple Snare Hit',
  '29:Snare|Sleishman Maple Snare Alt',
  '30:Snare|Sleishman Maple Snare Drag',
  '31:Snare|Sleishman Maple Snare RimSHot',
  '32:Snare|Sleishman Maple Snare XStick',
  '33:Snare|Sleishman Acrylic Snare Hit',
  '34:Snare|Sleishman Acrylic Snare Alt',
  '35:Snare|Sleishman Acrylic Snare RimShot',
  '36:Snare|Sleishman Acrylic Snare Drag',
  '37:Snare|Sleishman Acrylic Snare XStick',
  '38:Snare|Yamaha Bamboo (Sn Off) Hit',
  '39:Snare|Yamaha Bamboo (Sn Off) XStick',
  '40:Snare|Yamaha Bamboo (Sn Off) RimShot',
  '41:Snare|Ti Snare (Amped) Hit',
  '42:Snare|Ti Snare (Amped) Alt',
  '43:Snare|Ti Snare (Amped) Drag',
  '44:Snare|Ti Snare (Amped) RimShot',
  '45:Snare|Ti Snare (Amped) XStick',
  '46:Snare|Armstrong Concert Snare RimClick',
  '47:Snare|Armstrong Concert Snare Hit',
  '48:Snare|Armstrong Concert Snare Drag',
  '49:Snare|Armstrong Concert Snare RimShot',
  '50:Snare|Armstrong Concert Snare XStick',
  '51:Snare|Haynes Sig. Snare Brush Hit',
  '52:Snare|Haynes Sig. Snare Bush XStick',
  '53:Snare|Haynes Sig. Snare RimShot',
  '54:Snare|Haynes Sig. Snare Hit',
  '55:Snare|Haynes Sig. Snare Alt',
  '56:Snare|Haynes Sig. Snare RimShot',
  '57:Snare|Haynes Sig. Snare XStick',
  '58:Snare|Haynes Sig. Snare (Sn Off) Hit',
  '59:Snare|Haynes Sig. Snare (Sn Off) RimShot',
  '60:Snare|Haynes Sig. Snare Drag',
  '61:Tom|Birch 10 Tom Hit',
  '62:Tom|Birch 10 Tom RimShot',
  '63:Tom|Birch 10 Tom RimClick',
  '64:Tom|Birch 12 Tom Hit',
  '65:Tom|Birch 12 Tom RimShot',
  '66:Tom|Birch 12 Tom RimClick',
  '67:Tom|Birch 16 Tom Hit',
  '68:Tom|Birch 16 Tom RimShot',
  '69:Tom|Birch 16 Tom RimClick',
  '70:Tom|Maple 10 Tom Hit',
  '71:Tom|Maple 10 Tom RimShot',
  '72:Tom|Maple 10 Tom RimClick',
  '73:Tom|Maple 12 Tom Hit',
  '74:Tom|Maple 12 Tom RimShot',
  '75:Tom|Maple 12 Tom RimClick',
  '76:Tom|Maple 14 Tom Hit',
  '77:Tom|Maple 14 Tom RimShot',
  '78:Tom|Maple 14 Tom RimClick',
  '79:Tom|Maple 16 Tom Hit',
  '80:Tom|Maple 16 Tom RimShot',
  '81:Tom|Maple 16 Tom RimClick',
  '82:Hi-hat|Dark Jazz HH Pedal',
  '83:Hi-hat|Dark Jazz HH Closed Tip',
  '84:Hi-hat|Dark Jazz HH Quarter Shoulder',
  '85:Hi-hat|Dark Jazz HH Half Shoulder',
  '86:Hi-hat|Dark Jazz HH 3Quarter Shoulder',
  '87:Hi-hat|Dark Jazz HH Open Shoulder',
  '88:Hi-hat|Bright HH Pedal',
  '89:Hi-hat|Bright HH Closed Tip',
  '90:Hi-hat|Bright HH Quarter Shoulder',
  '91:Hi-hat|Bright HH Half Shoulder',
  '92:Hi-hat|Bright HH 3Quarter Shoulder',
  '93:Hi-hat|Bright HH Open Shoulder',
  '94:Ride|TurkishJazz Ride 22 Sizzle Bell',
  '95:Ride|TurkishJazz Ride 22 Sizzle Bow',
  '96:Ride|TurkishJazz Ride 22 Sizzle Edge',
  '97:Ride|TurkishWide Ride 20 Bell',
  '98:Ride|TurkishWide Ride 20 Bow',
  '99:Ride|TurkishWide Ride 20 Edge',
  '100:Ride|TurkishMaster Vintage Ride 22 Bell',
  '101:Ride|TurkishMaster Vintage Ride 22 Bow',
  '102:Ride|TurkishMaster Vintage Ride 22 Edge',
  '103:Cymbal|TurkishTraditional Crash Ride 18 Bell',
  '104:Cymbal|TurkishTraditional Crash Ride 18 Bow',
  '105:Cymbal|TurkishTraditional Crash Ride 18 Edge',
  '106:Cymbal|TurkishClassic Crash 16 Bow',
  '107:Cymbal|TurkishClassic Crash 16 Edge',
  '108:Cymbal|TurkishSplash 10 Edge',
  '109:Cymbal|Orchestral 20 Sus',
  '110:Cymbal|Old Wuhan 20 Bell',
  '111:Cymbal|Old Wuhan 20 Bow',
  '112:Cymbal|Old Wuhan 20 Edge',
  '113:Percussion|Timbale High Head-Rim *',
  '114:Percussion|Timbale Low Head-Rim *',
  '115:Percussion|Wood Block_1 High',
  '116:Percussion|Wood Block_2 Low',
  '117:Percussion|Egg Shaker',
  '118:Percussion|Can Shaker',
  '119:Percussion|LP Cowbell Tip',
  '120:Percussion|LP Cowbell Shoulder',
  '121:Percussion|Agogo High',
  '122:Percussion|Agogo Low',
  '123:Percussion|Finger Snap',
  '124:Percussion|Finger Snaps',
  '125:Percussion|Finger Cymbal',
  '126:Percussion|Gong',
]

export default mapper(raw)
