import mapper from './mapper'

const raw = [
  '1:Percussion|Tumba Thump',
  '2:Percussion|Tumba Open',
  '3:Percussion|Quinto Slap',
  '4:Percussion|Quinto Hit',
  '5:Percussion|Cajon High',
  '6:Percussion|Cajon High Slap',
  '7:Percussion|Cajon Mid',
  '8:Percussion|Cajon Low',
  '9:Percussion|Clave',
  '10:Percussion|Djembe Open',
  '11:Percussion|Djembe Mute',
  '12:Percussion|Djembe Slap',
  '13:Percussion|Dynamic Bongo High',
  '14:Percussion|Dynamic Bongo Low',
  '15:Percussion|Darbuka Center',
  '16:Percussion|Darbuka Rim',
  '17:Percussion|Tambourine with Stick',
  '18:Percussion|Udu Strike',
  '19:Percussion|Udu Scoop',
  '20:Percussion|Doumbek Center',
  '21:Percussion|Doumbek Rim',
  '22:Kick|Bop Kick',
  '23:Kick|General Kick',
  '24:Kick|EKick',
  '25:Kick|Funk Kick',
  '26:Kick|Jazz Kick',
  '27:Kick|Metal Kick',
  '28:Kick|Rock Kick',
  '29:Kick|Thor Kick',
  '30:Snare|Thor Snare Head',
  '31:Snare|Thor Snare X-Stick',
  '32:Snare|Thor Snare Drag',
  '33:Snare|Reggae Snare Head',
  '34:Snare|Reggae Snare X-Stick',
  '35:Snare|Reggae Snare Drag',
  '36:Snare|Reggae Snare Off',
  '37:Snare|Modern Snare Head',
  '38:Snare|Modern Snare Drag',
  '39:Snare|ESnare',
  '40:Snare|Clap',
  '41:Snare|Group Claps',
  '42:Snare|Blues Snare Head',
  '43:Snare|Blues Snare X-Stick',
  '44:Snare|Blues Snare Drag',
  '45:Snare|Latin Snare Head',
  '46:Snare|Latin Snare X-Stick',
  '47:Snare|Latin Snare Drag',
  '48:Snare|Soul Snare Head',
  '49:Snare|Soul Snare X-Stick',
  '50:Snare|Soul Drag',
  '51:Snare|Brush Snare Head',
  '52:Snare|Brush Snare Tap',
  '53:Snare|Brush Snare Swirl',
  '54:Snare|HD Snare Head',
  '55:Snare|HD Snare Alt',
  '56:Snare|HD Snare Rimshot',
  '57:Snare|HD Snare X-Stick',
  '58:Snare|HD Snare Off',
  '59:Snare|HD Snare Off Rimshot',
  '60:Tom|Jazz Tom 1',
  '61:Tom|Jazz Tom 2',
  '62:Tom|Jazz Tom 3',
  '63:Tom|Jazz Tom 4',
  '64:Tom|Gated Tom 1',
  '65:Tom|Gated Tom 2',
  '66:Tom|Gated Tom 3',
  '67:Tom|Gated Tom 4',
  '68:Tom|80s Tom High',
  '69:Tom|80s Tom Low',
  '70:Tom|Rock Tom 1',
  '71:Tom|Rock Tom 2',
  '72:Tom|Rock Tom 3',
  '73:Tom|Rock Tom 4',
  '74:Tom|ETom High',
  '75:Tom|ETom Low',
  '76:Tom|70s Tom 1',
  '77:Tom|70s Tom 2',
  '78:Tom|70s Tom 3',
  '79:Tom|Brush Tom 1',
  '80:Tom|Brush Tom 2',
  '81:Hi-hat|EHat',
  '82:Hi-hat|Dark Hat Pedal',
  '83:Hi-hat|Dark Hat Closed',
  '84:Hi-hat|Dark Hat 1/4',
  '85:Hi-hat|Dark Hat 1/2',
  '86:Hi-hat|Dark Hat 3/4',
  '87:Hi-hat|Dark Hat Open',
  '88:Hi-hat|Bright Hat Pedal',
  '89:Hi-hat|Bright Hat Closed',
  '90:Hi-hat|Bright Hat 1/4',
  '91:Hi-hat|Bright Hat 1/2',
  '92:Hi-hat|Bright Hat 3/4',
  '93:Hi-hat|Bright Hat Open',
  '94:Ride|Sizzle Ride Bell',
  '95:Ride|Sizzle Ride Bow',
  '96:Ride|Sizzle Ride Edge',
  '97:Ride|Jazz Ride Bow',
  '98:Ride|Jazz Ride Bell',
  '99:Ride|Mega Ride Bow',
  '100:Ride|Mega Ride Bell',
  '101:Cymbal|16 Crash Choke',
  '102:Cymbal|11 Splash',
  '103:Cymbal|12 Splash',
  '104:Cymbal|16 Crash',
  '105:Cymbal|18 Crash',
  '106:Cymbal|Bright China',
  '107:Cymbal|China Edge',
  '108:Cymbal|Brush Ride',
  '109:Cymbal|18 Brush Sizzle',
  '110:Cymbal|16 Brush',
  '111:Cymbal|18 Dark Choke',
  '112:Cymbal|16 Dark Choke',
  '113:Percussion|Dynamic Timbale High',
  '114:Percussion|Dynamic Timbale Low',
  '115:Percussion|Block 1',
  '116:Percussion|Block 2',
  '117:Percussion|Short Shaker',
  '118:Percussion|Long Shaker',
  '119:Percussion|Dynamic Cowbell 1',
  '120:Percussion|Dynamic Cowbell 2',
  '121:Percussion|Agogo High',
  '122:Percussion|Agogo Low',
  '123:Percussion|Finger Snap',
  '124:Percussion|Finger Snaps',
  '125:Percussion|Finger Cymbal',
  '126:Percussion|Gong',
]

export default mapper(raw)
