import deepFreeze from 'deep-freeze'
import storeFactory from '../../src/store'
import { selectMapping } from '../../src/action-creators/mapping'

describe('mapping actions', () => {
  let store

  const mapping = {
    name: '',
    entries: [],
    available: [
      { name: 'stompblock', label: 'STOMPBLOCK' },
      { name: 'emrichNumber1', label: 'John Emrich - Articulations #1' },
    ],
  }

  deepFreeze(mapping)

  describe('loadMapping 1', () => {
    beforeAll(() => {
      store = storeFactory({ mapping }, false, true)
      store.dispatch(selectMapping('emrichNumber1'))
    })

    it('should succeed', () => {
      expect(store.getState().mapping).toEqual({
        available: [
          { label: 'STOMPBLOCK', name: 'stompblock' },
          { label: 'John Emrich - Articulations #1', name: 'emrichNumber1' },
        ],
        entries: [
          { group: 'Perc', name: 'Tumba Thump', note: 1 },
          { group: 'Perc', name: 'Tumba Open', note: 2 },
          { group: 'Perc', name: 'Quinto Slap', note: 3 },
          { group: 'Perc', name: 'Quinto Open Trio ', note: 4 },
          { group: 'Perc', name: 'Cajon 10 Open', note: 5 },
          { group: 'Perc', name: 'Cajon 10 Open', note: 6 },
          { group: 'Perc', name: 'Cajon 12 Open', note: 7 },
          { group: 'Perc', name: 'Cajon 12 Open', note: 8 },
          { group: 'Perc', name: 'Clave', note: 9 },
          { group: 'Perc', name: 'Djembe 1 Open', note: 10 },
          { group: 'Perc', name: 'Djembe 2 Mute', note: 11 },
          { group: 'Perc', name: 'Djembe Slap', note: 12 },
          { group: 'Perc', name: 'Bongo High Open', note: 13 },
          { group: 'Perc', name: 'Bongo Low Open', note: 14 },
          { group: 'Perc', name: 'Darbuka Center', note: 15 },
          { group: 'Perc', name: 'Darbuka Rim', note: 16 },
          { group: 'Perc', name: 'DS Tambourine', note: 17 },
          { group: 'Perc', name: 'Udu Strike', note: 18 },
          { group: 'Perc', name: 'Udu Scoop', note: 19 },
          { group: 'Perc', name: 'Doumbek Center', note: 20 },
          { group: 'Perc', name: 'Doumbek Rim', note: 21 },
          { group: 'Kicks', name: 'Bop Kick', note: 22 },
          { group: 'Kicks', name: 'General Kick', note: 23 },
          { group: 'Kicks', name: 'Sleishman 20', note: 24 },
          { group: 'Kicks', name: 'Tonal 1', note: 25 },
          { group: 'Kicks', name: 'Ti BD 26 ', note: 26 },
          { group: 'Kicks', name: 'Remo 18 Djembe ', note: 27 },
          { group: 'Snares', name: 'Sleishman Maple Snare Hit', note: 28 },
          { group: 'Snares', name: 'Sleishman Maple Snare Alt', note: 29 },
          { group: 'Snares', name: 'Sleishman Maple Snare Drag', note: 30 },
          { group: 'Snares', name: 'Sleishman Maple Snare RimSHot', note: 31 },
          { group: 'Snares', name: 'Sleishman Maple Snare XStick', note: 32 },
          { group: 'Snares', name: 'Sleishman Acrylic Snare Hit', note: 33 },
          { group: 'Snares', name: 'Sleishman Acrylic Snare Alt', note: 34 },
          { group: 'Snares', name: 'Sleishman Acrylic Snare RimShot', note: 35 },
          { group: 'Snares', name: 'Sleishman Acrylic Snare Drag', note: 36 },
          { group: 'Snares', name: 'Sleishman Acrylic Snare XStick', note: 37 },
          { group: 'Snares', name: 'Yamaha Bamboo ', note: 38 },
          { group: 'Snares', name: 'Yamaha Bamboo ', note: 39 },
          { group: 'Snares', name: 'Yamaha Bamboo ', note: 40 },
          { group: 'Snares', name: 'Ti Snare ', note: 41 },
          { group: 'Snares', name: 'Ti Snare ', note: 42 },
          { group: 'Snares', name: 'Ti Snare ', note: 43 },
          { group: 'Snares', name: 'Ti Snare ', note: 44 },
          { group: 'Snares', name: 'Ti Snare ', note: 45 },
          { group: 'Snares', name: 'Armstrong Concert Snare RimClick', note: 46 },
          { group: 'Snares', name: 'Armstrong Concert Snare Hit', note: 47 },
          { group: 'Snares', name: 'Armstrong Concert Snare Drag', note: 48 },
          { group: 'Snares', name: 'Armstrong Concert Snare RimShot', note: 49 },
          { group: 'Snares', name: 'Armstrong Concert Snare XStick', note: 50 },
          { group: 'Snares', name: 'Haynes Sig', note: 51 },
          { group: 'Snares', name: 'Haynes Sig', note: 52 },
          { group: 'Snares', name: 'Haynes Sig', note: 53 },
          { group: 'Snares', name: 'Haynes Sig', note: 54 },
          { group: 'Snares', name: 'Haynes Sig', note: 55 },
          { group: 'Snares', name: 'Haynes Sig', note: 56 },
          { group: 'Snares', name: 'Haynes Sig', note: 57 },
          { group: 'Snares', name: 'Haynes Sig', note: 58 },
          { group: 'Snares', name: 'Haynes Sig', note: 59 },
          { group: 'Snares', name: 'Haynes Sig', note: 60 },
          { group: 'Toms', name: 'Birch 10 Tom Hit', note: 61 },
          { group: 'Toms', name: 'Birch 10 Tom RimShot', note: 62 },
          { group: 'Toms', name: 'Birch 10 Tom RimClick', note: 63 },
          { group: 'Toms', name: 'Birch 12 Tom Hit', note: 64 },
          { group: 'Toms', name: 'Birch 12 Tom RimShot', note: 65 },
          { group: 'Toms', name: 'Birch 12 Tom RimClick', note: 66 },
          { group: 'Toms', name: 'Birch 16 Tom Hit', note: 67 },
          { group: 'Toms', name: 'Birch 16 Tom RimShot', note: 68 },
          { group: 'Toms', name: 'Birch 16 Tom RimClick', note: 69 },
          { group: 'Toms', name: 'Maple 10 Tom Hit', note: 70 },
          { group: 'Toms', name: 'Maple 10 Tom RimShot', note: 71 },
          { group: 'Toms', name: 'Maple 10 Tom RimClick', note: 72 },
          { group: 'Toms', name: 'Maple 12 Tom Hit', note: 73 },
          { group: 'Toms', name: 'Maple 12 Tom RimShot', note: 74 },
          { group: 'Toms', name: 'Maple 12 Tom RimClick', note: 75 },
          { group: 'Toms', name: 'Maple 14 Tom Hit', note: 76 },
          { group: 'Toms', name: 'Maple 14 Tom RimShot', note: 77 },
          { group: 'Toms', name: 'Maple 14 Tom RimClick', note: 78 },
          { group: 'Toms', name: 'Maple 16 Tom Hit', note: 79 },
          { group: 'Toms', name: 'Maple 16 Tom RimShot', note: 80 },
          { group: 'Toms', name: 'Maple 16 Tom RimClick', note: 81 },
          { group: 'Hats', name: 'Dark Jazz HH Pedal', note: 82 },
          { group: 'Hats', name: 'Dark Jazz HH Closed Tip', note: 83 },
          { group: 'Hats', name: 'Dark Jazz HH Quarter Shoulder', note: 84 },
          { group: 'Hats', name: 'Dark Jazz HH Half Shoulder', note: 85 },
          { group: 'Hats', name: 'Dark Jazz HH 3Quarter Shoulder', note: 86 },
          { group: 'Hats', name: 'Dark Jazz HH Open Shoulder', note: 87 },
          { group: 'Hats', name: 'Bright HH Pedal', note: 88 },
          { group: 'Hats', name: 'Bright HH Closed Tip', note: 89 },
          { group: 'Hats', name: 'Bright HH Quarter Shoulder', note: 90 },
          { group: 'Hats', name: 'Bright HH Half Shoulder', note: 91 },
          { group: 'Hats', name: 'Bright HH 3Quarter Shoulder', note: 92 },
          { group: 'Hats', name: 'Bright HH Open Shoulder', note: 93 },
          { group: 'Rides', name: 'TurkishJazz Ride 22 Sizzle Bell', note: 94 },
          { group: 'Rides', name: 'TurkishJazz Ride 22 Sizzle Bow', note: 95 },
          { group: 'Rides', name: 'TurkishJazz Ride 22 Sizzle Edge', note: 96 },
          { group: 'Rides', name: 'TurkishWide Ride 20 Bell', note: 97 },
          { group: 'Rides', name: 'TurkishWide Ride 20 Bow', note: 98 },
          { group: 'Rides', name: 'TurkishWide Ride 20 Edge', note: 99 },
          { group: 'Rides', name: 'TurkishMaster Vintage Ride 22 Bell', note: 100 },
          { group: 'Rides', name: 'TurkishMaster Vintage Ride 22 Bow', note: 101 },
          { group: 'Rides', name: 'TurkishMaster Vintage Ride 22 Edge', note: 102 },
          { group: 'Cymbals', name: 'TurkishTraditional Crash Ride 18 Bell', note: 103 },
          { group: 'Cymbals', name: 'TurkishTraditional Crash Ride 18 Bow', note: 104 },
          { group: 'Cymbals', name: 'TurkishTraditional Crash Ride 18 Edge', note: 105 },
          { group: 'Cymbals', name: 'TurkishClassic Crash 16 Bow', note: 106 },
          { group: 'Cymbals', name: 'TurkishClassic Crash 16 Edge', note: 107 },
          { group: 'Cymbals', name: 'TurkishSplash 10 Edge', note: 108 },
          { group: 'Cymbals', name: 'Orchestral 20 Sus', note: 109 },
          { group: 'Cymbals', name: 'Old Wuhan 20 Bell', note: 110 },
          { group: 'Cymbals', name: 'Old Wuhan 20 Bow', note: 111 },
          { group: 'Cymbals', name: 'Old Wuhan 20 Edge', note: 112 },
          { group: 'Perc', name: 'Timbale High Head', note: 113 },
          { group: 'Perc', name: 'Timbale Low Head', note: 114 },
          { group: 'Perc', name: 'Wood Block_1 High', note: 115 },
          { group: 'Perc', name: 'Wood Block_2 Low', note: 116 },
          { group: 'Perc', name: 'Egg Shaker', note: 117 },
          { group: 'Perc', name: 'Can Shaker', note: 118 },
          { group: 'Perc', name: 'LP Cowbell Tip', note: 119 },
          { group: 'Perc', name: 'LP Cowbell Shoulder', note: 120 },
          { group: 'Perc', name: 'Agogo High', note: 121 },
          { group: 'Perc', name: 'Agogo Low', note: 122 },
          { group: 'Perc', name: 'Finger Snap', note: 123 },
          { group: 'Perc', name: 'Finger Snaps', note: 124 },
          { group: 'Perc', name: 'Finger Cymbal', note: 125 },
          { group: 'Perc', name: 'Gong', note: 126 },
        ],
        name: 'emrichNumber1',
      })
    })
  })

  describe('loadMapping 2', () => {
    beforeAll(() => {
      store = storeFactory({ mapping }, false, true)
      store.dispatch(selectMapping('stompblock'))
    })

    it('should succeed', () => {
      expect(store.getState().mapping).toEqual({
        available: [
          { label: 'STOMPBLOCK', name: 'stompblock' },
          { label: 'John Emrich - Articulations #1', name: 'emrichNumber1' },
        ],
        entries: [
          { group: 'Perc', name: 'Tumba Thump', note: 1 },
          { group: 'Perc', name: 'Tumba Open', note: 2 },
          { group: 'Perc', name: 'Quinto Slap', note: 3 },
          { group: 'Perc', name: 'Quinto Hit', note: 4 },
          { group: 'Perc', name: 'Cajon High', note: 5 },
          { group: 'Perc', name: 'Cajon High Slap', note: 6 },
          { group: 'Perc', name: 'Cajon Mid', note: 7 },
          { group: 'Perc', name: 'Cajon Low', note: 8 },
          { group: 'Perc', name: 'Clave', note: 9 },
          { group: 'Perc', name: 'Djembe Open', note: 10 },
          { group: 'Perc', name: 'Djembe Mute', note: 11 },
          { group: 'Perc', name: 'Djembe Slap', note: 12 },
          { group: 'Perc', name: 'Dynamic Bongo High', note: 13 },
          { group: 'Perc', name: 'Dynamic Bongo Low', note: 14 },
          { group: 'Perc', name: 'Darbuka Center', note: 15 },
          { group: 'Perc', name: 'Darbuka Rim', note: 16 },
          { group: 'Perc', name: 'Tambourine with Stick', note: 17 },
          { group: 'Perc', name: 'Udu Strike', note: 18 },
          { group: 'Perc', name: 'Udu Scoop', note: 19 },
          { group: 'Perc', name: 'Doumbek Center', note: 20 },
          { group: 'Perc', name: 'Doumbek Rim', note: 21 },
          { group: 'Kicks', name: 'Bop Kick', note: 22 },
          { group: 'Kicks', name: 'General Kick', note: 23 },
          { group: 'Kicks', name: 'EKick', note: 24 },
          { group: 'Kicks', name: 'Funk Kick', note: 25 },
          { group: 'Kicks', name: 'Jazz Kick', note: 26 },
          { group: 'Kicks', name: 'Metal Kick', note: 27 },
          { group: 'Kicks', name: 'Rock Kick', note: 28 },
          { group: 'Kicks', name: 'Thor Kick', note: 29 },
          { group: 'Snares', name: 'Thor Snare Head', note: 30 },
          { group: 'Snares', name: 'Thor Snare X', note: 31 },
          { group: 'Snares', name: 'Thor Snare Drag', note: 32 },
          { group: 'Snares', name: 'Reggae Snare Head', note: 33 },
          { group: 'Snares', name: 'Reggae Snare X', note: 34 },
          { group: 'Snares', name: 'Reggae Snare Drag', note: 35 },
          { group: 'Snares', name: 'Reggae Snare Off', note: 36 },
          { group: 'Snares', name: 'Modern Snare Head', note: 37 },
          { group: 'Snares', name: 'Modern Snare Drag', note: 38 },
          { group: 'Snares', name: 'ESnare', note: 39 },
          { group: 'Snares', name: 'Clap', note: 40 },
          { group: 'Snares', name: 'Group Claps', note: 41 },
          { group: 'Snares', name: 'Blues Snare Head', note: 42 },
          { group: 'Snares', name: 'Blues Snare X', note: 43 },
          { group: 'Snares', name: 'Blues Snare Drag', note: 44 },
          { group: 'Snares', name: 'Latin Snare Head', note: 45 },
          { group: 'Snares', name: 'Latin Snare X', note: 46 },
          { group: 'Snares', name: 'Latin Snare Drag', note: 47 },
          { group: 'Snares', name: 'Soul Snare Head', note: 48 },
          { group: 'Snares', name: 'Soul Snare X', note: 49 },
          { group: 'Snares', name: 'Soul Drag', note: 50 },
          { group: 'Snares', name: 'Brush Snare Head', note: 51 },
          { group: 'Snares', name: 'Brush Snare Tap', note: 52 },
          { group: 'Snares', name: 'Brush Snare Swirl', note: 53 },
          { group: 'Snares', name: 'HD Snare Head', note: 54 },
          { group: 'Snares', name: 'HD Snare Alt', note: 55 },
          { group: 'Snares', name: 'HD Snare Rimshot', note: 56 },
          { group: 'Snares', name: 'HD Snare X', note: 57 },
          { group: 'Snares', name: 'HD Snare Off', note: 58 },
          { group: 'Snares', name: 'HD Snare Off Rimshot', note: 59 },
          { group: 'Toms', name: 'Jazz Tom 1', note: 60 },
          { group: 'Toms', name: 'Jazz Tom 2', note: 61 },
          { group: 'Toms', name: 'Jazz Tom 3', note: 62 },
          { group: 'Toms', name: 'Jazz Tom 4', note: 63 },
          { group: 'Toms', name: 'Gated Tom 1', note: 64 },
          { group: 'Toms', name: 'Gated Tom 2', note: 65 },
          { group: 'Toms', name: 'Gated Tom 3', note: 66 },
          { group: 'Toms', name: 'Gated Tom 4', note: 67 },
          { group: 'Toms', name: '80s Tom High', note: 68 },
          { group: 'Toms', name: '80s Tom Low', note: 69 },
          { group: 'Toms', name: 'Rock Tom 1', note: 70 },
          { group: 'Toms', name: 'Rock Tom 2', note: 71 },
          { group: 'Toms', name: 'Rock Tom 3', note: 72 },
          { group: 'Toms', name: 'Rock Tom 4', note: 73 },
          { group: 'Toms', name: 'ETom High', note: 74 },
          { group: 'Toms', name: 'ETom Low', note: 75 },
          { group: 'Toms', name: '70s Tom 1', note: 76 },
          { group: 'Toms', name: '70s Tom 2', note: 77 },
          { group: 'Toms', name: '70s Tom 3', note: 78 },
          { group: 'Toms', name: 'Brush Tom 1', note: 79 },
          { group: 'Toms', name: 'Brush Tom 2', note: 80 },
          { group: 'Hats', name: 'EHat', note: 81 },
          { group: 'Hats', name: 'Dark Hat Pedal', note: 82 },
          { group: 'Hats', name: 'Dark Hat Closed', note: 83 },
          { group: 'Hats', name: 'Dark Hat 1/4', note: 84 },
          { group: 'Hats', name: 'Dark Hat 1/2', note: 85 },
          { group: 'Hats', name: 'Dark Hat 3/4', note: 86 },
          { group: 'Hats', name: 'Dark Hat Open', note: 87 },
          { group: 'Hats', name: 'Bright Hat Pedal', note: 88 },
          { group: 'Hats', name: 'Bright Hat Closed', note: 89 },
          { group: 'Hats', name: 'Bright Hat 1/4', note: 90 },
          { group: 'Hats', name: 'Bright Hat 1/2', note: 91 },
          { group: 'Hats', name: 'Bright Hat 3/4', note: 92 },
          { group: 'Hats', name: 'Bright Hat Open', note: 93 },
          { group: 'Rides', name: 'Sizzle Ride Bell', note: 94 },
          { group: 'Rides', name: 'Sizzle Ride Bow', note: 95 },
          { group: 'Rides', name: 'Sizzle Ride Edge', note: 96 },
          { group: 'Rides', name: 'Jazz Ride Bow', note: 97 },
          { group: 'Rides', name: 'Jazz Ride Bell', note: 98 },
          { group: 'Rides', name: 'Mega Ride Bow', note: 99 },
          { group: 'Rides', name: 'Mega Ride Bell', note: 100 },
          { group: 'Cymbals', name: '16 Crash Choke', note: 101 },
          { group: 'Cymbals', name: '11 Splash', note: 102 },
          { group: 'Cymbals', name: '12 Splash', note: 103 },
          { group: 'Cymbals', name: '16 Crash', note: 104 },
          { group: 'Cymbals', name: '18 Crash', note: 105 },
          { group: 'Cymbals', name: 'Bright China', note: 106 },
          { group: 'Cymbals', name: 'China Edge', note: 107 },
          { group: 'Cymbals', name: 'Brush Ride', note: 108 },
          { group: 'Cymbals', name: '18 Brush Sizzle', note: 109 },
          { group: 'Cymbals', name: '16 Brush', note: 110 },
          { group: 'Cymbals', name: '18 Dark Choke', note: 111 },
          { group: 'Cymbals', name: '16 Dark Choke', note: 112 },
          { group: 'Perc', name: 'Dynamic Timbale High', note: 113 },
          { group: 'Perc', name: 'Dynamic Timbale Low', note: 114 },
          { group: 'Perc', name: 'Block 1', note: 115 },
          { group: 'Perc', name: 'Block 2', note: 116 },
          { group: 'Perc', name: 'Short Shaker', note: 117 },
          { group: 'Perc', name: 'Long Shaker', note: 118 },
          { group: 'Perc', name: 'Dynamic Cowbell 1', note: 119 },
          { group: 'Perc', name: 'Dynamic Cowbell 2', note: 120 },
          { group: 'Perc', name: 'Agogo High', note: 121 },
          { group: 'Perc', name: 'Agogo Low', note: 122 },
          { group: 'Perc', name: 'Finger Snap', note: 123 },
          { group: 'Perc', name: 'Finger Snaps', note: 124 },
          { group: 'Perc', name: 'Finger Cymbal', note: 125 },
          { group: 'Perc', name: 'Gong', note: 126 },
        ],
        name: 'stompblock',
      })
    })
  })
})
