export const WEB_MIDI_ERRORED = 'WEB_MIDI_ERRORED';
export const GET_MIDI_DEVICES = 'GET_MIDI_DEVICES';
export const GET_SYSEX_VERSION = 'GET_SYSEX_VERSION';
export const RELOAD_SYSEX = 'RELOAD_SYSEX';
export const RECEIVED_VERSION = 'RECEIVED_VERSION';
export const RECEIVED_ALL_TRIMS = 'RECEIVED_ALL_TRIMS';
export const USED_CHANGED_TRIM = 'USED_CHANGED_TRIM';
export const USED_CHANGED_TRIM_END = 'USED_CHANGED_TRIM_END';
