export const STOMPBLOCK_DEVICE_ID = 0x6B;

export const CURRENT_ANVIL_VERSION = 22;

export const CHANNEL = 10;

export const SYSEX_MSG_GET_VERSION = 0x01;
export const SYSEX_MSG_RECEIVE_VERSION = 0x02;
export const SYSEX_MSG_GET_ALL = 0x03;
export const SYSEX_MSG_RECEIVE_ALL = 0x04;
export const SYSEX_MSG_SET_MUTE_ENABLED = 0x05;
export const SYSEX_MSG_SET_THRU_ENABLED = 0x06;
export const SYSEX_MSG_SET_MUTE_GROUPS_ENABLED = 0x07;
export const SYSEX_MSG_PLAY_NOTE = 0x08;
export const SYSEX_MSG_SET_ITEM = 0x09;
export const SYSEX_MSG_RECEIVED_MUTE_ENABLED = 0x0A;
export const SYSEX_MSG_RECEIVED_THRU_ENABLED = 0x0B;
export const SYSEX_MSG_RECEIVED_MUTE_GROUPS_ENABLED = 0x0C;
export const SYSEX_MSG_FACTORY_RESET = 0x7E;
