export default [
  '1:Perc|Tumba Thump',
  '2:Perc|Tumba Open',
  '3:Perc|Quinto Slap',
  '4:Perc|Quinto Hit',
  '5:Perc|Cajon High',
  '6:Perc|Cajon High Slap',
  '7:Perc|Cajon Mid',
  '8:Perc|Cajon Low',
  '9:Perc|Clave',
  '10:Perc|Djembe Open',
  '11:Perc|Djembe Mute',
  '12:Perc|Djembe Slap',
  '13:Perc|Dynamic Bongo High',
  '14:Perc|Dynamic Bongo Low',
  '15:Perc|Darbuka Center',
  '16:Perc|Darbuka Rim',
  '17:Perc|Tambourine with Stick',
  '18:Perc|Udu Strike',
  '19:Perc|Udu Scoop',
  '20:Perc|Doumbek Center',
  '21:Perc|Doumbek Rim',
  '22:Kicks|Bop Kick',
  '23:Kicks|General Kick',
  '24:Kicks|EKick',
  '25:Kicks|Funk Kick',
  '26:Kicks|Jazz Kick',
  '27:Kicks|Metal Kick',
  '28:Kicks|Rock Kick',
  '29:Kicks|Thor Kick',
  '30:Snares|Thor Snare Head',
  '31:Snares|Thor Snare X-Stick',
  '32:Snares|Thor Snare Drag',
  '33:Snares|Reggae Snare Head',
  '34:Snares|Reggae Snare X-Stick',
  '35:Snares|Reggae Snare Drag',
  '36:Snares|Reggae Snare Off',
  '37:Snares|Modern Snare Head',
  '38:Snares|Modern Snare Drag',
  '39:Snares|ESnare',
  '40:Snares|Clap',
  '41:Snares|Group Claps',
  '42:Snares|Blues Snare Head',
  '43:Snares|Blues Snare X-Stick',
  '44:Snares|Blues Snare Drag',
  '45:Snares|Latin Snare Head',
  '46:Snares|Latin Snare X-Stick',
  '47:Snares|Latin Snare Drag',
  '48:Snares|Soul Snare Head',
  '49:Snares|Soul Snare X-Stick',
  '50:Snares|Soul Drag',
  '51:Snares|Brush Snare Head',
  '52:Snares|Brush Snare Tap',
  '53:Snares|Brush Snare Swirl',
  '54:Snares|HD Snare Head',
  '55:Snares|HD Snare Alt',
  '56:Snares|HD Snare Rimshot',
  '57:Snares|HD Snare X-Stick',
  '58:Snares|HD Snare Off',
  '59:Snares|HD Snare Off Rimshot',
  '60:Toms|Jazz Tom 1',
  '61:Toms|Jazz Tom 2',
  '62:Toms|Jazz Tom 3',
  '63:Toms|Jazz Tom 4',
  '64:Toms|Gated Tom 1',
  '65:Toms|Gated Tom 2',
  '66:Toms|Gated Tom 3',
  '67:Toms|Gated Tom 4',
  '68:Toms|80s Tom High',
  '69:Toms|80s Tom Low',
  '70:Toms|Rock Tom 1',
  '71:Toms|Rock Tom 2',
  '72:Toms|Rock Tom 3',
  '73:Toms|Rock Tom 4',
  '74:Toms|ETom High',
  '75:Toms|ETom Low',
  '76:Toms|70s Tom 1',
  '77:Toms|70s Tom 2',
  '78:Toms|70s Tom 3',
  '79:Toms|Brush Tom 1',
  '80:Toms|Brush Tom 2',
  '81:Hats|EHat',
  '82:Hats|Dark Hat Pedal',
  '83:Hats|Dark Hat Closed',
  '84:Hats|Dark Hat 1/4',
  '85:Hats|Dark Hat 1/2',
  '86:Hats|Dark Hat 3/4',
  '87:Hats|Dark Hat Open',
  '88:Hats|Bright Hat Pedal',
  '89:Hats|Bright Hat Closed',
  '90:Hats|Bright Hat 1/4',
  '91:Hats|Bright Hat 1/2',
  '92:Hats|Bright Hat 3/4',
  '93:Hats|Bright Hat Open',
  '94:Rides|Sizzle Ride Bell',
  '95:Rides|Sizzle Ride Bow',
  '96:Rides|Sizzle Ride Edge',
  '97:Rides|Jazz Ride Bow',
  '98:Rides|Jazz Ride Bell',
  '99:Rides|Mega Ride Bow',
  '100:Rides|Mega Ride Bell',
  '101:Cymbals|16 Crash Choke',
  '102:Cymbals|11 Splash',
  '103:Cymbals|12 Splash',
  '104:Cymbals|16 Crash',
  '105:Cymbals|18 Crash',
  '106:Cymbals|Bright China',
  '107:Cymbals|China Edge',
  '108:Cymbals|Brush Ride',
  '109:Cymbals|18 Brush Sizzle',
  '110:Cymbals|16 Brush',
  '111:Cymbals|18 Dark Choke',
  '112:Cymbals|16 Dark Choke',
  '113:Perc|Dynamic Timbale High',
  '114:Perc|Dynamic Timbale Low',
  '115:Perc|Block 1',
  '116:Perc|Block 2',
  '117:Perc|Short Shaker',
  '118:Perc|Long Shaker',
  '119:Perc|Dynamic Cowbell 1',
  '120:Perc|Dynamic Cowbell 2',
  '121:Perc|Agogo High',
  '122:Perc|Agogo Low',
  '123:Perc|Finger Snap',
  '124:Perc|Finger Snaps',
  '125:Perc|Finger Cymbal',
  '126:Perc|Gong',
];
